[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
nixpacksVersion = "1.11.0"

[deploy]
startCommand = "python run_bot.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[service]
autoDeploy = true
autoRollback = true

[engines]
python = "3.10"