# Railway deployment configuration

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
python_version = "3.9"

[variables]
PYTHON_VERSION = "3.9"