services:
  - type: web
    name: guard-shin-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: python app.py
    numInstances: 1
    healthCheckPath: /
    pullRequestPreviewsEnabled: false
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DISABLE_COMMAND_REGISTRATION
        value: true
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GUARD_SHIN_BOT_TOKEN
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false