services:
  # A Node.js web service that hosts both the dashboard and the Discord bot
  - type: web
    name: guard-shin-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.cjs
    autoDeploy: true
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        value: 1361873604882731008
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: PAYMENT_WEBHOOK_URL
        fromService:
          name: guard-shin-bot
          type: web
          property: url
        append: /api/webhook/payment
      - key: UPDATE_WEBHOOK_URL
        fromService:
          name: guard-shin-bot
          type: web
          property: url
        append: /api/webhook/update
    healthCheckPath: /