name: Discord Bot

on:
  push:
    branches: [ main ]
    paths:
      - 'bot/**'
      - 'discord-bot/**'
  workflow_dispatch:

jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Create lock file if needed
      run: |
        if [ ! -f package-lock.json ]; then
          echo "Lock file not found, generating with npm install"
          npm install --package-lock-only
        fi
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Build bot
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Register Discord slash commands
      run: node github_actions_config/register-commands.js
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        
    - name: Send Discord notification
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.UPDATE_WEBHOOK_URL }}
      run: |
        if [ "$DISCORD_WEBHOOK" != "" ]; then
          if [ "${{ job.status }}" == "success" ]; then
            curl -H "Content-Type: application/json" -d '{"username": "GitHub Actions", "content": "Lifeless rose updated: 🤖 Discord bot commands updated successfully!"}' $DISCORD_WEBHOOK
          else
            curl -H "Content-Type: application/json" -d '{"username": "GitHub Actions", "content": "Lifeless rose updated: ❌ Discord bot command registration failed! Check GitHub Actions for details."}' $DISCORD_WEBHOOK
          fi
        fi