name: Deploy Discord Bot to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'discord-bot/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f discord-bot/requirements.txt ]; then pip install -r discord-bot/requirements.txt; fi
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Setup Railway CLI
        run: npm install -g @railway/cli
      
      - name: Prepare Environment
        run: |
          cd discord-bot
          echo "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}" > .env
          echo "GUARD_SHIN_BOT_TOKEN=${GUARD_SHIN_BOT_TOKEN}" >> .env
          echo "UPDATE_WEBHOOK_URL=${UPDATE_WEBHOOK_URL}" >> .env
      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          GUARD_SHIN_BOT_TOKEN: ${{ secrets.GUARD_SHIN_BOT_TOKEN }}
          UPDATE_WEBHOOK_URL: ${{ secrets.UPDATE_WEBHOOK_URL }}
        run: |
          cd discord-bot
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway link || railway project create --name "guard-shin-bot"
          railway up --detach
      
      - name: Set Environment Variables on Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd discord-bot
          railway variables set DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
          railway variables set GUARD_SHIN_BOT_TOKEN=${{ secrets.GUARD_SHIN_BOT_TOKEN }}
          railway variables set UPDATE_WEBHOOK_URL=${{ secrets.UPDATE_WEBHOOK_URL }}
      
      - name: Send Deployment Notification
        if: always()
        run: |
          if [ -n "${{ secrets.UPDATE_WEBHOOK_URL }}" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{"content": "🤖 Guard-shin Bot: Deployment ${{ job.status }} at $(date)"}' \
              ${{ secrets.UPDATE_WEBHOOK_URL }}
          fi
