name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create dummy package.json if not exists
        run: |
          if [ ! -f "package.json" ]; then
            echo '{"name":"guard-shin-dashboard","version":"0.0.0","private":true,"scripts":{"dev":"vite","build":"vite build"}}' > package.json
          fi
          cat package.json
      
      - name: Build website
        run: |
          # Create a .env file with the public Stripe key
          echo "VITE_STRIPE_PUBLIC_KEY=${{ secrets.VITE_STRIPE_PUBLIC_KEY }}" > .env
          echo "IS_GITHUB_PAGES=true" >> .env
          
          # Build the React application
          npm run build
        env:
          VITE_STRIPE_PUBLIC_KEY: ${{ secrets.VITE_STRIPE_PUBLIC_KEY }}
          IS_GITHUB_PAGES: 'true'
      
      # Create a 404.html that redirects to index.html for client-side routing
      - name: Create 404.html and index.html for client-side routing
        run: |
          if [ -d "dist" ]; then
            cp dist/index.html dist/404.html
          else
            mkdir -p dist
            echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Guard-shin Discord Bot</title><script>window.location.href="https://witherco.github.io/Guard-shin/#/";</script></head><body><p>Redirecting to Guard-shin Dashboard...</p></body></html>' > dist/index.html
            cp dist/index.html dist/404.html
          fi
      
      # Create a .nojekyll file to disable Jekyll processing
      - name: Create .nojekyll file
        run: touch dist/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}