# Railway deployment configuration for Guard-shin Discord Bot

[build]
builder = "nixpacks"
buildCommand = "pip install -r discord-bot/requirements.txt"

[deploy]
startCommand = "python discord-bot/run.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[nixpacks]
python_version = "3.10"

[variables]
PYTHON_VERSION = "3.10"