name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages

      - name: Send Discord Notification
        if: github.ref == 'refs/heads/main' && success()
        run: |
          curl -X POST ${{ secrets.UPDATE_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
            "content": "Lifeless rose updated: New deployment completed successfully",
            "embeds": [
              {
                "title": "Guard-shin Dashboard Deployment",
                "description": "Dashboard has been successfully deployed to GitHub Pages.",
                "color": 3066993,
                "fields": [
                  {
                    "name": "Commit",
                    "value": "${{ github.sha }}"
                  },
                  {
                    "name": "Triggered by",
                    "value": "${{ github.actor }}"
                  },
                  {
                    "name": "Status",
                    "value": "✅ Success"
                  }
                ],
                "footer": {
                  "text": "Guard-shin Dashboard"
                },
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }
            ]
          }'