name: Deploy Discord Bot to Railway

on:
  push:
    branches:
      - main
    paths:
      - 'cogs/**'
      - 'discord-bot/**'
      - 'run_bot.py'
      - '.github/workflows/deploy-discord-bot.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_railway.txt
          
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Copy files to discord-bot directory
        run: |
          # Make sure bot files are properly organized
          if [ -f "run_bot.py" ]; then
            cp run_bot.py discord-bot/run.py
          fi
          if [ -d "cogs" ]; then
            cp -r cogs/* discord-bot/cogs/
          fi
          
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: ./discord-bot
        run: railway up