name: Deploy Discord Bot to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'discord-bot/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        working-directory: ./discord-bot
        run: pip install -r requirements.txt
      
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "guard-shin-bot"
          directory: "./discord-bot"
          
      - name: Set environment variables on Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          npm i -g @railway/cli
          cd discord-bot
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway variables set DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
          railway variables set GUARD_SHIN_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
          railway variables set UPDATE_WEBHOOK_URL=${{ secrets.UPDATE_WEBHOOK_URL }}
          
      - name: Send deployment webhook
        run: |
          if [ -n "${{ secrets.UPDATE_WEBHOOK_URL }}" ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -d '{"content": "Lifeless rose updated: Bot has been deployed to Railway via GitHub Actions"}' \
              ${{ secrets.UPDATE_WEBHOOK_URL }}
          fi