name: Deploy Discord Bot to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'discord-bot/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      
      - name: Deploy to Railway
        working-directory: ./discord-bot
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          UPDATE_WEBHOOK_URL: ${{ secrets.UPDATE_WEBHOOK_URL }}